use lazy_static::lazy_static;
use parking_lot::RwLock;
use proto_ecs::core::ids;
use proto_ecs::get_id;
use proto_ecs::systems::common::*;
use topological_sort::TopologicalSort;

type GlobalSystemID = u32; // TODO Change to a smaller type
type GSStageMap = StageMap<fn()>; // TODO Not sure what the signature of global system functions is

pub trait GlobalSystemDesc {
    const NAME: &'static str;
    const NAME_CRC: u32;
}

#[derive(Debug)]
pub struct LocalSystemRegistryEntry {
    pub id: GlobalSystemID,
    pub name: &'static str,
    pub name_crc: u32,
    pub dependencies: Vec<Dependency>,
    pub functions: GSStageMap,
    pub before: Vec<GlobalSystemID>,
    pub after: Vec<GlobalSystemID>,
    pub set_id_fn: fn(GlobalSystemID), // Only used for init, don't use it manually
}

#[derive(Debug, Default)]
pub struct LocalSystemRegistry {
    entries: Vec<LocalSystemRegistryEntry>,
    is_initialized: bool,
}

impl LocalSystemRegistry {
    #[inline]
    pub fn new() -> Self {
        LocalSystemRegistry::default()
    }

    #[inline]
    fn get_temp_global_registry() -> &'static RwLock<TempRegistryLambdas> {
        &LOCAL_SYSTEM_REGISTRY_TEMP
    }

    pub fn register_lambda(lambda: TempRegistryLambda) {
        LocalSystemRegistry::get_temp_global_registry()
            .write()
            .push(lambda)
    }

    #[inline]
    pub fn get_global_registry() -> &'static RwLock<Self> {
        &GLOBAL_SYSTEM
    }

    pub fn register(&mut self, entry: LocalSystemRegistryEntry) {
        self.entries.push(entry);
    }

    #[inline]
    pub fn is_initialized(&self) -> bool {
        self.is_initialized
    }

    /// Initialize the global registry
    pub fn initialize() {
        let mut registry = LocalSystemRegistry::get_global_registry().write();
        assert!(
            !registry.is_initialized,
            "Local System registry was already initialized!"
        );

        let mut locals_register_fns = TempRegistryLambdas::new();
        let mut globals_register_fns = LocalSystemRegistry::get_temp_global_registry().write();

        // Clear globals
        std::mem::swap(&mut locals_register_fns, &mut globals_register_fns);

        registry.init(locals_register_fns);
    }

    /// Initialize this registry entry
    pub fn init(&mut self, registry_fns: TempRegistryLambdas) {
        registry_fns.into_iter().for_each(|lambda| lambda(self));
        self.set_toposort_ids();

        self.entries
            .sort_unstable_by(|this, other| this.id.cmp(&other.id));

        self.is_initialized = true;
    }

    #[inline]
    pub fn get_entry_by_id(&self, id: GlobalSystemID) -> &LocalSystemRegistryEntry {
        debug_assert!((id as usize) < self.entries.len(), "Invalid ID");
        &self.entries[id as usize]
    }

    /// Set ids for local systems based on the topological ordering
    /// generated by the `before` and `after` dependencies. Local systems
    /// can then be sorted by id to get the order in which they should be run
    fn set_toposort_ids(&mut self) {
        let mut ts: TopologicalSort<GlobalSystemID> = TopologicalSort::new();
        let source_node = GlobalSystemID::default();
        for entry in self.entries.iter() {
            let entry_crc = entry.name_crc;
            ts.add_dependency(source_node, entry_crc);

            // Sanity check
            debug_assert!(
                source_node != entry.name_crc,
                "Source node should be a value never reachable by the crc"
            );
            for &other_crc in entry.before.iter() {
                ts.add_dependency(entry_crc, other_crc);
            }

            for &other_crc in entry.after.iter() {
                ts.add_dependency(other_crc, entry_crc);
            }
        }

        let source_node_vec = ts.pop_all();
        debug_assert!(
            source_node_vec.len() == 1,
            "The first dependency should be only the source node"
        );
        debug_assert!(
            source_node_vec[0] == source_node,
            "The first dependency should be the source node"
        );
        let mut dependency_order = vec![];
        while !ts.is_empty() {
            let mut non_dependents = ts.pop_all();
            if non_dependents.is_empty() && !ts.is_empty() {
                // If there's cyclic dependencies,
                // then the popped list is empty and ts.len > 0,
                // See: https://docs.rs/topological-sort/latest/topological_sort/struct.TopologicalSort.html#method.pop_all
                // TODO: better error handling, report cyclic dependencies
                panic!("Cyclic dependencies between local systems!");
            }

            // Non-dependents are elements that do not depend on anything else.
            // Sort them by value to get a deterministic ordering each time.
            // Since they don't depend on each other, the actual order doesn't matter.
            non_dependents.sort();
            dependency_order.extend(non_dependents);
        }

        for entry in self.entries.iter_mut() {
            let id = dependency_order
                .iter()
                .position(|&crc| entry.name_crc == crc)
                .unwrap();
            entry.id = id as GlobalSystemID;
            (entry.set_id_fn)(id as GlobalSystemID);
        }
    }

    /// Get the entry for a specific LocalSystem
    pub fn get_entry<S>(&self) -> &LocalSystemRegistryEntry
    where
        S: ids::IDLocator + GlobalSystemDesc,
    {
        self.get_entry_by_id(get_id!(S))
    }

    pub fn set_dependencies<S>(&mut self, before: Vec<GlobalSystemID>, after: Vec<GlobalSystemID>)
    where
        S: ids::IDLocator + GlobalSystemDesc,
    {
        // We won't allow changing dependencies in runtime
        debug_assert!(
            !self.is_initialized,
            "You can only set dependencies before initializing local systems"
        );
        let entry = &mut self.entries[get_id!(S) as usize];
        entry.before = before;
        entry.after = after;
    }
}

pub type TempRegistryLambda = Box<dyn FnOnce(&mut LocalSystemRegistry) + Sync + Send + 'static>;
type TempRegistryLambdas = Vec<TempRegistryLambda>;

lazy_static! {

    // This registry holds functions that register a local system.
    // It's filled before main so that we choose when to call this functions.
    static ref LOCAL_SYSTEM_REGISTRY_TEMP: RwLock<TempRegistryLambdas> =
        RwLock::from(TempRegistryLambdas::new());
}

lazy_static! {
    static ref GLOBAL_SYSTEM: RwLock<LocalSystemRegistry> =
        RwLock::from(LocalSystemRegistry::new());
}
