[package]
name = "proto_ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
crc32fast = { version = "*" }
ctor = "0.2.5"
ecs_macros = { version = "0.1.0", path = "ecs_macros" }
lazy_static = "1.4.0"
nohash-hasher = "0.2.0"
once_cell = "1.18.0"
parking_lot = "0.12.1"
topological-sort = "0.2.2"
vector-map = "1.0.1"
