// Key codes stolen from here: 
// https://rust-sdl2.github.io/rust-sdl2/sdl2/keyboard/enum.Keycode.html
#[derive(Debug)]
pub enum Keycode {
    Backspace  ,
    Tab        ,
    Return     ,
    Escape     ,
    Space      ,
    Exclaim    ,
    Quotedbl   ,
    Hash       ,
    Dollar     ,
    Percent    ,
    Ampersand  ,
    Quote      ,
    LeftParen  ,
    RightParen ,
    Asterisk   ,
    Plus       ,
    Comma      ,
    Minus      ,
    Period     ,
    Slash      ,
    Num0       ,
    Num1       ,
    Num2       ,
    Num3       ,
    Num4       ,
    Num5       ,
    Num6       ,
    Num7       ,
    Num8       ,
    Num9       ,
    Colon      ,
    Semicolon  ,
    Less       ,
    Equals     ,
    Greater    ,
    Question   ,
    At         ,
    LeftBracket,
    Backslash  ,
    RightBracke,
    Caret      ,
    Underscore ,
    Backquote  ,
    A          ,
    B          ,
    C          ,
    D          ,
    E          ,
    F          ,
    G          ,
    H          ,
    I          ,
    J          ,
    K          ,
    L          ,
    M          ,
    N          ,
    O          ,
    P          ,
    Q          ,
    R          ,
    S          ,
    T          ,
    U          ,
    V          ,
    W          ,
    X          ,
    Y          ,
    Z          ,
    Delete     ,
    CapsLock   ,
    F1         ,
    F2         ,
    F3         ,
    F4         ,
    F5         ,
    F6         ,
    F7         ,
    F8         ,
    F9         ,
    F10        ,
    F11        ,
    F12        ,
    PrintScreen,
    ScrollLock ,
    Pause      ,
    Insert     ,
    Home       ,
    PageUp     ,
    End        ,
    PageDown   ,
    Right      ,
    Left       ,
    Down       ,
    Up         ,
    NumLockClea,
    KpDivide   ,
    KpMultiply ,
    KpMinus    ,
    KpPlus     ,
    KpEnter    ,
    Enter      , 
    Kp1        ,
    Kp2        ,
    Kp3        ,
    Kp4        ,
    Kp5        ,
    Kp6        ,
    Kp7        ,
    Kp8        ,
    Kp9        ,
    Kp0        ,
    KpPeriod   ,
    Application,
    Power      ,
    KpEquals   ,
    F13        ,
    F14        ,
    F15        ,
    F16        ,
    F17        ,
    F18        ,
    F19        ,
    F20        ,
    F21        ,
    F22        ,
    F23        ,
    F24        ,
    Execute    ,
    Help       ,
    Menu       ,
    Select     ,
    Stop       ,
    Again      ,
    Undo       ,
    Cut        ,
    Copy       ,
    Paste      ,
    Find       ,
    Mute       ,
    VolumeUp   ,
    VolumeDown ,
    KpComma    ,
    KpEqualsAS4,
    AltErase   ,
    Sysreq     ,
    Cancel     ,
    Clear      ,
    Prior      ,
    Return2    ,
    Separator  ,
    Out        ,
    Oper       ,
    ClearAgain ,
    CrSel      ,
    ExSel      ,
    Kp00       ,
    Kp000      ,
    ThousandsSe,
    DecimalSepa,
    CurrencyUni,
    CurrencySub,
    KpLeftParen,
    KpRightPare,
    KpLeftBrace,
    KpRightBrac,
    KpTab      ,
    KpBackspace,
    KpA        ,
    KpB        ,
    KpC        ,
    KpD        ,
    KpE        ,
    KpF        ,
    KpXor      ,
    KpPower    ,
    KpPercent  ,
    KpLess     ,
    KpGreater  ,
    KpAmpersand,
    KpDblAmpers,
    KpVerticalB,
    KpDblVertic,
    KpColon    ,
    KpHash     ,
    KpSpace    ,
    KpAt       ,
    KpExclam   ,
    KpMemStore ,
    KpMemRecall,
    KpMemClear ,
    KpMemAdd   ,
    KpMemSubtra,
    KpMemMultip,
    KpMemDivide,
    KpPlusMinus,
    KpClear    ,
    KpClearEntr,
    KpBinary   ,
    KpOctal    ,
    KpDecimal  ,
    KpHexadecim,
    LCtrl      ,
    LShift     ,
    LAlt       ,
    LGui       ,
    RCtrl      ,
    RShift     ,
    RAlt       ,
    RGui       ,
    Mode       ,
    AudioNext  ,
    AudioPrev  ,
    AudioStop  ,
    AudioPlay  ,
    AudioMute  ,
    MediaSelect,
    Www        ,
    Mail       ,
    Calculator ,
    Computer   ,
    AcSearch   ,
    AcHome     ,
    AcBack     ,
    AcForward  ,
    AcStop     ,
    AcRefresh  ,
    AcBookmarks,
    BrightnessD,
    BrightnessU,
    DisplaySwit,
    KbdIllumTog,
    KbdIllumDow,
    KbdIllumUp ,
    Eject      ,
    Sleep      ,
    Unknown    ,
}
